/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: 'node',
  testMatch: ['**/tests/**/*.test.js', '**/src/__tests__/**/*.test.js'],
  collectCoverageFrom: [
    'src/**/*.js',
    '!src/__tests__/**',
    '!src/logs/**',
    '!src/scripts/**',
    '!src/empty.md',
  ],
  coverageReporters: ['text', 'lcov', 'html'],
  coverageDirectory: 'coverage',
  setupFilesAfterEnv: [],
  testTimeout: 10000,
  clearMocks: true,
  restoreMocks: true,
  moduleNameMapper: {
    '^\\.\\./\\.\\./api/middlewares/logger\\.middleware$': '<rootDir>/src/api/middlewares/logger.middleware',
    '^\\.\\./__mocks__/logger\\.mock$': '<rootDir>/tests/__mocks__/logger.mock.js',
    '^\\.\\./\\.\\./services/(.*)$': '<rootDir>/src/services/$1',
    '^\\.\\./\\.\\./models/(.*)$': '<rootDir>/src/models/$1',
    '^\\.\\./\\.\\./api/(.*)$': '<rootDir>/src/api/$1',
    '^\\.\\./\\.\\./utils/(.*)$': '<rootDir>/src/utils/$1',
    '^\\.\\./\\.\\./config$': '<rootDir>/src/config/index.js',
    '^\\.\\./\\.\\./config/(.*)$': '<rootDir>/src/config/$1',
    '^\\.\\./\\.\\./middlewares/(.*)$': '<rootDir>/src/api/middlewares/$1',
    '^\\.\\./\\.\\./validators/(.*)$': '<rootDir>/src/api/validators/$1',
    '^\\.\\./\\.\\./controllers/(.*)$': '<rootDir>/src/api/controllers/$1',
    '^\\.\\./\\.\\./\\.\\./services/(.*)$': '<rootDir>/src/services/$1',
    '^\\.\\./\\.\\./\\.\\./models/(.*)$': '<rootDir>/src/models/$1',
    '^\\.\\./\\.\\./\\.\\./api/(.*)$': '<rootDir>/src/api/$1',
    '^\\.\\./\\.\\./\\.\\./utils/(.*)$': '<rootDir>/src/utils/$1',
    '^\\.\\./\\.\\./\\.\\./config$': '<rootDir>/src/config/index.js',
    '^\\.\\./\\.\\./\\.\\./config/(.*)$': '<rootDir>/src/config/$1',
    '^\\.\\./\\.\\./\\.\\./middlewares/(.*)$': '<rootDir>/src/api/middlewares/$1',
    '^\\.\\./\\.\\./\\.\\./validators/(.*)$': '<rootDir>/src/api/validators/$1',
    '^\\.\\./\\.\\./\\.\\./controllers/(.*)$': '<rootDir>/src/api/controllers/$1',
  },
};
