import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * weeklyReportPdf.ts
 * ─────────────────────────────────────────────────────────────────────────
 * Renders the AI Weekly Report PDF entirely client-side from the JSON the
 * server returns (GET /api/ai/weekly-report). jsPDF + jspdf-autotable are
 * already installed in this project's package.json but were not yet wired
 * up to a feature — this is the first real usage of jspdf-autotable.
 *
 * Keeping PDF rendering on the client (not the server) means:
 *  - no server-side headless-browser/PDF dependency to maintain
 *  - the report always matches what the user sees in their own session
 *  - it's instant to demo for the Enterprise ($99/mo) sales pitch
 * ─────────────────────────────────────────────────────────────────────────
 */

export interface WeeklyReportData {
  generatedAt: string;
  periodLabel: string;
  totalValue: number;
  weeklyChange: number;
  weeklyChangePercentage: number;
  allTimeProfit: number;
  allTimeProfitPercentage: number;
  assetCount: number;
  healthScore: {
    diversificationScore: number;
    concentrationWarning: string | null;
    groupExposure: Record<string, number>;
  };
  topMovers: Array<{
    symbol: string;
    name: string;
    value: number;
    profitLoss: number;
    profitLossPercentage: number;
  }>;
  taxLoss: {
    opportunityCount: number;
    totalPotentialTaxSavings: number;
    topOpportunities: Array<{
      symbol: string;
      lossAmount: number;
      estimatedTaxSavings: number;
      action: string;
    }>;
  };
  narrative: string;
  narrativeSource: 'ai' | 'template';
}

export function generateWeeklyReportPdf(report: WeeklyReportData, userName?: string) {
  const doc = new jsPDF();
  const fmt = (n: number) => `$${Number(n || 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
  let y = 20;

  // Header
  doc.setFontSize(18);
  doc.text('NeoFin — AI Weekly Report', 14, y);
  y += 8;
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    `${userName ? userName + ' · ' : ''}${report.periodLabel} · Generated ${new Date(report.generatedAt).toLocaleString()}`,
    14,
    y
  );
  doc.setTextColor(0);
  y += 12;

  // Summary block
  doc.setFontSize(13);
  doc.text('Portfolio Summary', 14, y);
  y += 7;
  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: [
      ['Total Value', fmt(report.totalValue)],
      ['Weekly Change', `${fmt(report.weeklyChange)} (${report.weeklyChangePercentage.toFixed(2)}%)`],
      ['All-Time Profit', `${fmt(report.allTimeProfit)} (${report.allTimeProfitPercentage.toFixed(2)}%)`],
      ['Asset Count', String(report.assetCount)],
      ['Diversification Score', `${report.healthScore.diversificationScore}/100`],
    ],
    theme: 'striped',
    styles: { fontSize: 9 },
    headStyles: { fillColor: [99, 102, 241] },
  });
  // @ts-ignore - jspdf-autotable attaches lastAutoTable to the doc instance
  y = (doc as any).lastAutoTable.finalY + 10;

  // AI narrative
  doc.setFontSize(13);
  doc.text('Weekly Narrative', 14, y);
  y += 7;
  doc.setFontSize(10);
  const narrativeLines = doc.splitTextToSize(report.narrative, 180);
  doc.text(narrativeLines, 14, y);
  y += narrativeLines.length * 5 + 8;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    report.narrativeSource === 'ai' ? 'Narrative generated by Gemini AI.' : 'Narrative generated by NeoFin\'s local reasoning engine (AI unavailable).',
    14,
    y
  );
  doc.setTextColor(0);
  y += 10;

  // Top movers table
  if (report.topMovers?.length) {
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFontSize(13);
    doc.text('Top Movers This Week', 14, y);
    y += 7;
    autoTable(doc, {
      startY: y,
      head: [['Symbol', 'Name', 'Value', 'P&L', 'P&L %']],
      body: report.topMovers.map((m) => [
        m.symbol,
        m.name,
        fmt(m.value),
        fmt(m.profitLoss),
        `${m.profitLossPercentage.toFixed(2)}%`,
      ]),
      theme: 'striped',
      styles: { fontSize: 9 },
      headStyles: { fillColor: [99, 102, 241] },
    });
    // @ts-ignore
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // Tax-loss harvesting section (the Enterprise differentiator)
  if (y > 240) { doc.addPage(); y = 20; }
  doc.setFontSize(13);
  doc.text('Tax-Loss Harvesting Opportunities', 14, y);
  y += 7;

  if (report.taxLoss.opportunityCount === 0) {
    doc.setFontSize(10);
    doc.text('No tax-loss harvesting opportunities this week.', 14, y);
    y += 10;
  } else {
    doc.setFontSize(10);
    doc.text(
      `${report.taxLoss.opportunityCount} opportunities · estimated savings ${fmt(report.taxLoss.totalPotentialTaxSavings)}`,
      14,
      y
    );
    y += 6;
    autoTable(doc, {
      startY: y,
      head: [['Symbol', 'Unrealised Loss', 'Est. Tax Savings', 'Suggested Action']],
      body: report.taxLoss.topOpportunities.map((o) => [
        o.symbol,
        fmt(o.lossAmount),
        fmt(o.estimatedTaxSavings),
        o.action,
      ]),
      theme: 'striped',
      styles: { fontSize: 8, cellWidth: 'wrap' },
      columnStyles: { 3: { cellWidth: 90 } },
      headStyles: { fillColor: [99, 102, 241] },
    });
  }

  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text(
    'This report is for informational purposes only and is not financial or tax advice.',
    14,
    doc.internal.pageSize.getHeight() - 10
  );

  doc.save(`neofin-weekly-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}